### ISSUE TITLE
Support for PerfBuffer?

### ISSUE THREAD

**Issue by jsoo1** [fujita/libbpf-async#3]
The ring buffer is clearly the best choice but is not supported on all kernels. I love the ringbuffer interface you provide, would a perfbuffer implementation be possible, too?

**Comment by fujita** [comment]
It's on my list but I don't use the perfbuffer so low priority for me. It would be great if someone would implement it.

**Comment by jsoo1** [comment]
I'd be happy to try if you can point me in the right direction.

**Comment by jsoo1** [comment]
I won't be able to get to this 😞
